Repository MatthewHerbst/react-to-print, pull requests merged in 2019-04, with the labels that each got.

#111 Rewrite to Typescript + fully Webpack build
  .eslintrc.js
  .gitignore
  example/ComponentToPrint/index.js
  example/ComponentToPrint/index.tsx
  example/index.js
  example/index.tsx
  index.d.ts
  index.html
  package-lock.json
  package.json
  rollup.config.js
  src/index.js
  src/index.tsx
  tsconfig.json
  webpack.config.js
  webpack.dev.config.js
  webpack.prod.config.js
Labels: TypeScript

#116 Fixed import bug
  package.json
  webpack.prod.config.js
Labels: bug

#119 Version 2.1.1 + CHANGELOG
  CHANGELOG.md
  package.json
Labels: Chrome, documentation
